# Generated by Django 2.2.1 on 2019-05-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('hike_date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('distance', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('created_date', models.DateField()),
                ('picture', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='HikeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike_group', to='hike.Hike')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike_group', to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='hike.Hike')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='accounts.Profile')),
            ],
        ),
    ]
