# Generated by Django 2.2.1 on 2019-05-21 23:54


from django.db import migrations
from django.contrib.auth.models import User


def seed(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Hike = apps.get_model('hike', 'Hike')
    Comments = apps.get_model('hike', 'Comments')
    HikeGroup = apps.get_model('hike', 'HikeGroup')

    user1 = User(username='bobby', password='testing1234', email='bob@gmail.com')
    user1.save()
    user2 = User(username='cat', password='testing1234')
    user2.save()
    user3 = User(username='dog', password='testing1234')
    user3.save()
    

    profile_one = Profile(user_id=user1.id, bio='HI bio one', picture='https://static.thenounproject.com/png/630729-200.png')
    profile_two = Profile(user_id=user2.id, bio='HI bio two', picture='http://cdn.onlinewebfonts.com/svg/download_525162.png')
    profile_three = Profile(user_id=user3.id, bio='HI bio three', picture='https://png.pngtree.com/svg/20170602/b7c3ca6e9e.svg')
    
    profile_one.save()
    profile_two.save()
    profile_three.save()

    hike_one = Hike(
    profile = profile_one,
    title = 'hike_test_one',
    description = 'hiking test one is pretty fun',
    hike_date = '1993-01-21',
    latitude = '12345678',
    longitude = '987654321',
    street = '225 bush st',
    city = 'Sans-Francisco',
    country = 'California',
    zipcode = '94587',
    distance = '30',
    difficulty = '9',
    created_date = '2022-11-23',
    picture = 'http://3tsll33cscvk11pae33oze51-wpengine.netdna-ssl.com/wp-content/uploads/2017/05/san-francisco-hiking-trails-andy-goldsworthy-presidio.png'
    )
    
    hike_two = Hike(
    profile = profile_two,
    title = 'hike_test_two',
    description = 'hiking test two is pretty okay',
    hike_date = '2007-03-21',
    latitude = '12345678',
    longitude = '987654321',
    street = '631 Montgermery st',
    city = 'Sans-Francisco',
    country = 'California',
    zipcode = '99962',
    distance = '10',
    difficulty = '2',
    created_date = '2020-09-12',
    picture = 'https://previews.123rf.com/images/maximkabb/maximkabb1610/maximkabb161000018/64698997-hiking-trails-through-giant-redwoods-in-muir-forest-near-san-francisco-california-usa.jpg'
    )
    
    hike_three = Hike(
    profile = profile_three,
    title = 'hike_test_three',
    description = 'hiking test three is Awesome!',
    hike_date = '2013-02-23',
    latitude = '12345678',
    longitude = '987654321',
    street = '902 doorbell st',
    city = 'Sans-Francisco',
    country = 'California',
    zipcode = '92123',
    distance = '5',
    difficulty = '1',
    created_date = '2010-10-21',
    picture = 'https://i.pinimg.com/736x/a3/ff/20/a3ff2004308b48ff11c1ffe2ae8c00c6--lovers-lane-san-francisco-california.jpg'
    )

    hike_one.save()
    hike_two.save()
    hike_three.save()

    Comments(hike = hike_one, profile = profile_one, body='Comment test 1', rating='6').save()
    Comments(hike = hike_two, profile = profile_two, body='Comment test 2', rating='1').save()
    Comments(hike = hike_three, profile = profile_three, body='Comment test 3', rating='9').save()

    HikeGroup(hike = hike_one, profile = profile_one).save()
    HikeGroup(hike = hike_two, profile = profile_two).save()
    HikeGroup(hike = hike_three, profile = profile_three).save()


def delete_both(apps, schema_editor):
    Profile = apps.get_model()
    Hike = apps.get_model()
    Comments = apps.get_model()
    HikeGroup = apps.get_model()
    Profile.objects.all().delete()
    Hike.objects.all().delete()
    Comments.objects.all().delete()
    HikeGroup.objects.all().delete()




class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, delete_both)
    ]