# Generated by Django 2.2.1 on 2019-05-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0001_initial'),
    ]

    operations = [
    ]
