# Generated by Django 2.2.1 on 2019-05-24 07:01

from django.db import migrations
from django.contrib.auth.models import User

def delete_both(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Hike = apps.get_model('hike', 'Hike')
    Comments = apps.get_model('hike', 'Comments')
    HikeGroup = apps.get_model('hike', 'HikeGroup')
    Comments.objects.all().delete()
    HikeGroup.objects.all().delete()
    Hike.objects.all().delete()
    Profile.objects.all().delete()
    User.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_both)
    ]
