# Generated by Django 2.2.1 on 2019-05-24 07:01

from django.db import migrations
from django.contrib.auth.models import User


def seed(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Hike = apps.get_model('hike', 'Hike')
    Comments = apps.get_model('hike', 'Comments')
    HikeGroup = apps.get_model('hike', 'HikeGroup')

    user1 = User(username='bob', password='testing1234', email='bob@gmail.com', first_name='Bob', last_name='Belcher')
    user1.save()
    user2 = User(username='alyson', password='testing1234', email='a@a.com', first_name='Alyson', last_name='Hannigan')
    user2.save()
    user3 = User(username='chris', password='testing1234', email='c@c.com', first_name='Chris', last_name='Hemsworth')
    user3.save()
    user4 = User(username='dora', password='testing1234', email='d@d.com', first_name='Dora', last_name='Explorer')
    user4.save()
    user5 = User(username='elle', password='testing1234', email='e@e.com', first_name='Elle', last_name='Woods')
    user5.save()
    user6 = User(username='fillory', password='testing1234', email='f@f.com', first_name='Fillorian', last_name='Lady')
    user6.save()
    user7 = User(username='ginger', password='testing1234', email='g@g.com', first_name='Ginger', last_name='Grant')
    user7.save()
    user8 = User(username='harry', password='testing1234', email='h@h.com', first_name='Harry', last_name='Potter')
    user8.save()
    user9 = User(username='ivy', password='testing1234', email='i@i.com', first_name='Poison', last_name='Ivy')
    user9.save()
    user10 = User(username='jerry', password='testing1234', email='j@j.com', first_name='Jerry', last_name='Seinfeld')
    user10.save()


    profile_one = Profile(user_id=user1.id, bio="Robert 'Bob' Belcher Jr. is a third-generation restaurateur. Bob runs Bob's Burgers with the help of his wife, Linda Belcher, and their three kids, Tina Belcher, Louise Belcher, and Gene Belcher. While poor with business management and cursed with an unlucky streak, his experience and skill in homemade cuisine has helped his restaurant stay afloat, in spite of seemingly constant financial uncertainty, providing for his family all the while.", picture='https://vignette.wikia.nocookie.net/bobsburgerpedia/images/9/95/Bobs-Burgers-Wiki_Archer_Bob_01a.png/revision/latest?cb=20160712225426')
    profile_two = Profile(user_id=user2.id, bio="Willow Danielle Rosenberg was a witch native to Sunnydale, California, founding member of the Scooby Gang, and the best friend and semi-official sidekick of the Slayer, Buffy Summers. Willow started out as a shy computer nerd, eventually developing her talents to become a powerful and assertive witch. Willow was introduced to the forces of magic by attempting a complex spell to re-ensoul Angel. To her own surprise, Willow tapped into considerable power during this ritual, and would come to practice witchcraft. Willow was quick to grasp basic spells and with support from her girlfriend Tara Maclay, her powers blossomed even more rapidly as did her self-confidence. Milestones in her magical career include the enjoining spell, taking on the Hell-Goddess Glory and surviving, resurrecting Buffy Summers, nearly ending the world, activating the world’s Potential Slayers and eventually, establishing herself as Earth’s most powerful witch.", picture='https://vignette.wikia.nocookie.net/buffy/images/6/62/Willow_tk.jpg/revision/latest/scale-to-width-down/1000?cb=20100319183627')
    profile_three = Profile(user_id=user3.id, bio="Chris Hemsworth was born in Melbourne, Australia, to Leonie (van Os), a teacher of English, and Craig Hemsworth, a social-services counselor. His brothers are actors Liam Hemsworth and Luke Hemsworth. He is of Dutch (from his immigrant maternal grandfather), Irish, English, Scottish, and German ancestry. His uncle, by marriage, was Rod Ansell, the bushman who inspired the film Crocodile Dundee (1986).", picture='https://m.media-amazon.com/images/M/MV5BMTYwMTUwNTAyOV5BMl5BanBnXkFtZTgwMTk1OTU5NzM@._V1_SX1777_CR0,0,1777,937_AL_.jpg')
    profile_four = Profile(user_id=user4.id, bio='HI bio four', picture='http://cdn.onlinewebfonts.com/svg/download_525162.png')
    profile_five = Profile(user_id=user5.id, bio='HI bio five', picture='http://cdn.onlinewebfonts.com/svg/download_525162.png')
    profile_six = Profile(user_id=user6.id, bio='Margo is a strong, independent woman who is not afraid to speak her mind and a high-spirited magician whose speciality is gossip, competition, and drama. Although at first sight, she may seem superficial, Margo is a keen observer. Margo has shown to be the most rational of the group during stressful situations, often being mistaken for cruel and bitter.', picture='https://media.vanityfair.com/photos/5abc3ecddd3307642814825f/master/w_1920,c_limit/margo-magicians-king-of-fillory.jpg')
    profile_seven = Profile(user_id=user7.id, bio="Any man worth his weight in hormones would give his right arm to be stuck on an island with Ginger Grant. Ginger is an alluring and sexy actress, reminiscent of Marilyn Monroe, who persists in worrying about her gowns, her appearance, her career, and Hollywood gossip. Ginger follows a fascinating moral code. While Ginger's extraordinarily flirtatious and shapely, she never tried to advance her acting career on the casting couch. She's always willing to use her seductive powers or acting ability to help her fellow castaways. She diverts any visitor to the island, and she eagerly suggests plans of action based on parts she's played in movies. Ginger lives in Hollywood, California, and has an agent whose name we never learn.", picture='https://vignette.wikia.nocookie.net/gilligan5935/images/8/86/G57.jpg/revision/latest?cb=20141016230637')
    profile_eight = Profile(user_id=user8.id, bio="Harry James Potter (b. 31 July, 1980) was an English half-blood wizard, one of the most famous wizards of modern times. He was the only child and son of James and Lily Potter (née Evans), both members of the original Order of the Phoenix. Harry's birth was overshadowed by a prophecy, naming either himself or Neville Longbottom as the one with the power to vanquish Lord Voldemort. After half of the prophecy was reported to Voldemort courtesy of Severus Snape, Harry was chosen as the target due to his many similarities with the Dark Lord. This caused the Potter family to go into hiding. Voldemort made his first vain attempt to circumvent the prophecy when Harry was a year and three months old. During this attempt he murdered Harry's parents as they tried to protect him, but this unsuccessful attempt to kill Harry led to Voldemort's first downfall. This downfall marked the end of the First Wizarding War, and to Harry henceforth being known as the Boy-Who-Lived.", picture='https://vignette.wikia.nocookie.net/harrypotter/images/7/70/Harry-potter1-snape_limp.jpg/revision/latest/scale-to-width-down/1000')
    profile_nine = Profile(user_id=user9.id, bio="Poison Ivy is an enemy of Batman. She is depicted as one of the world's most prominent eco-terrorists. She is obsessed with plants, botany, and environmentalism. She uses toxins from plants and her own bloodstream for her criminal activities, which are usually aimed at protecting the natural environment. She creates love potions that ensnare Batman, Superman, and other strong-willed individuals. Fellow villain Harley Quinn is her recurring partner-in-crime and possibly her only human friend.", picture='https://cdn3.movieweb.com/i/article/AhBmYOoJsiQX68W6wJlk03y9BslvoZ/798:50/Gotham-City-Sirens-Art-Stone-Dushku-Poison-Ivy.jpg')
    profile_ten = Profile(user_id=user10.id, bio="Jerry's main friends are George Costanza, Cosmo Kramer and his ex-girlfriend Elaine Benes. Jerry (though not without exceptions) typically represents the voice of reason amidst George, Elaine, and Kramer's antics, and can be seen as the focal point of the foursome's relationship. Jerry is somewhat of an eternal optimist, as he rarely runs into major personal problems. Jerry is the only main character on the show to maintain the same career throughout the series (except for the episode where he is forced into bootlegging). Considering his job as a comedian, he is the most observational character, usually sarcastically commenting on his friends' quirky habits, almost essentially the 'New York Jew'-type character. He seems to have a new girlfriend every week, but the relationships usually end for fairly superficial reasons. He is also an almost obsessive compulsive neat freak; he once threw out a belt because it had touched a urinal, and once commented on finding out his toilet brush had been placed in the toilet that, 'I can replace that.'", picture='https://m.media-amazon.com/images/M/MV5BMTU5NTM5OTI1M15BMl5BanBnXkFtZTgwMTE1NzcxNDM@._V1_SY1000_CR0,0,649,1000_AL_.jpg')

    profile_one.save()
    profile_two.save()
    profile_three.save()
    profile_four.save()
    profile_five.save()
    profile_six.save()
    profile_seven.save()
    profile_eight.save()
    profile_nine.save()
    profile_ten.save()

    hike_one = Hike(
    profile = profile_one,
    title = "Devil’s Slide Trail",
    description = "If you’re looking for a mellow stroll along the coast, this is an easy-to-access jaunt from a pull-off along Highway 1. This paved, multiuse path along the old and now repurposed Highway 1 offers outstanding views of the ocean and is an excellent place to take the whole family. With free parking at both ends of the trail, you can hike it in either direction. Though mapped as a 2.5-mile-long out-and-back hike, you can easily cut this short, hiking only as far as your group wants to go. From the north, the trail starts off winding through coastal hills but quickly reaches the bluffs over the Pacific Ocean. Once on the bluffs, you’ll have views of the sea and, if you’re lucky with the weather, the Farallon Islands and Point Reyes. With abundant wildlife like coastal birds, seals and whales, kids and naturalists will relish this hike. There are benches on the side of the path if you want a break along the way, and the occasional interpretive sign offers up information about the area. All in all, this is a nice side trip to stretch your legs and enjoy the sunshine.",
    hike_date = '2019-05-31',
    latitude = 37.5798621,
    longitude = -122.5186716,
    street = '5929-5981 California Coastal Trail',
    city = 'Pacifica',
    country = 'CA',
    zipcode = 94044,
    distance = 2.5,
    difficulty = 1.2,
    created_date = '2018-11-23',
    picture = 'https://www.kcet.org/sites/kl/files/styles/kl_image_hero/public/thumbnails/image/cct_header_1.jpg?itok=Cfx837h3'
    )

    hike_two = Hike(
    profile = profile_two,
    title = 'Muir Woods Panoramic Loop',
    description = "If you’re looking for a slightly longer hike that traverses the lush forest of the coastal Bay Area, then the Panoramic Loop is for you. The hike winds through both the Muir Woods National Monument and Mount Tamalpais State Park. With interpretive programs and tree talks offered by the park service, there is plenty to do and learn about while in the area. Plus, the Junior Ranger Program and the Muir Woods Discovery Quest will surely keep the kiddos entertained. Keep in mind that parking and shuttle reservations are required when visiting Muir Woods National Monument, so you’ll have to plan ahead. Park at the Muir Woods Lower Annex Parking area and head out on the paved Redwood Creek Trail, passing the Muir Woods Visitor Center in about 0.2 miles. After about 0.6 miles, you’ll hike through the Cathedral Grove, an impressive grove of redwood trees. This trail can be quite busy but there are plenty of opportunities to step to the side of the trail or rest on one of the benches and enjoy the majestic surroundings.",
    hike_date = '2019-05-12',
    latitude = 37.8928503,
    longitude = -122.5746919,
    street = '1 Muir Woods Rd',
    city = 'Mill Valley',
    country = 'CA',
    zipcode = 94941,
    distance = 4.5,
    difficulty = 3.2,
    created_date = '2019-05-12',
    picture = 'http://www.redwoodhikes.com/Muir/Main1.jpg'
    )

    hike_three = Hike(
    profile = profile_three,
    title = 'Tomales Point Trail',
    description = "Point Reyes National Seashore is a wonderful place to spend a weekend with the family. With beautiful scenery, abundant wildlife and rich history, the park has appeal for everyone. There are a plethora of trails and hikes, educational programs and ranger-led activities to enjoy, as well as plenty of opportunities to explore and learn about the natural environment of the area. This out-and-back hike is located in the northwest corner of the park on Tomales Point. From the Bear Valley Visitor Center head north on Sir Francis Drake Boulevard, take a right onto Pierce Point Road and park at the historic Pierce Point Ranch in the Tule Elk Reserve. From here, follow the wide doubletrack Tomales Point Trail all the way to its terminus at the Lower Pierce Point Ranch. As the trail winds along the the crest of the point, you'll enjoy impressive scenery and likely catch glimpses of the tule elk that roam this area. Though the maintained doubletrack trail ends at the Lower Pierce Point Ranch, there is a well-defined, though unmaintained and rather sandy trail that heads all the way out to the tip of the point—the track does become fainter as you get closer to the bluffs. Once at the bluffs, enjoy the views of the ocean and Bird Rock, but stay on the main path; it is dangerous and not recommended to walk along the edge of the bluffs, which can be unstable, especially after wet weather. The way back is easy: Simply follow the same track back to the parking area. Though not a terribly strenuous hike, at almost 10 miles round trip, it is quite long. There is little shade, so come prepared with sunscreen, a hat, water and lunch or a snack.",
    hike_date = '2019-06-15',
    latitude = 38.18917,
    longitude = -122.9562542,
    street = 'Pierce Point Rd',
    city = 'Inverness',
    country = 'CA',
    zipcode = 94937,
    distance = 9.8,
    difficulty = 3.1,
    created_date = '2019-04-21',
    picture = 'https://www.rei.com/blog/wp-content/uploads/2019/01/Thule-Elk-1320x880.jpg'
    )
    hike_four = Hike(
    profile = profile_one,
    title = 'Quicksilver History Loop',
    description = "Located south of San Jose, Almaden Quicksilver County Park is rich with history and nature. Once the location of a mercury ore mining area, the park is now a recreation hotspot with opportunities for hiking, horseback riding, biking and more. The historic sites across the park make it easy to turn a simple hike into an educational experience. Plus, there are guided nature and history walks available—just call the park for more information. Time your visit for spring or early summer to enjoy a beautiful array of wildflowers while you learn about the past. To start your history tour, park at the Hacienda entrance; there is a display of old mining equipment here that is worth a gander on your way in. Begin hiking on the Mine Hill Trail, an old mining road that runs the length of the park. The trail gradually climbs along the hillsides, winding its way up through the woods. You’ll pass several historic sites, including an old tramway and a chimney that was once part of an ore processing furnace. Continue climbing, ignoring several trail intersections, until you reach the April Trail. Take this detour as it pops out of the woods and offers nice views of the bay and surrounding area.",
    hike_date = '2019-04-15',
    latitude = 37.1824621,
    longitude = -121.8527744,
    street = '21785 Almaden Rd',
    city = 'San Jose',
    country = 'CA',
    zipcode = 95120,
    distance = 8,
    difficulty = 3.5,
    created_date = '2019-04-02',
    picture = 'https://www.rei.com/blog/wp-content/uploads/2019/01/Old-English-Camp-1320x818.jpg'
    )
    hike_five = Hike(
    profile = profile_three,
    title = 'Berry Creek Falls Loop',
    description = "Though Big Basin Redwoods State Park, California’s oldest state park, is located near the ocean, it won’t feel coastal as you tromp through the dense forest. The opportunity to see the massive redwood stands lures most people to the park, but there is also an extensive trail system that can accommodate hikers of all experience levels. With hiking, camping and free park events to attend, Big Basin Redwoods State Park is an excellent place to spend the weekend or visit just for the day. Be sure to have your state parks pass, or pay the vehicle day-use fee. Starting from the headquarters parking lot, head south on the Skyline to the Sea Trail as it briefly climbs over the ridge before descending the other side. The trail drops and follows Kelley Creek, which then joins and becomes West Waddell Creek. Take your time and enjoy the sounds of the forest and flowing water as you hike. The shaded and serene setting of this trail is worth soaking in at amellow pace. When you turn onto Berry Creek Falls Trail, you'll be greeted with an amazing view of Berry Creek Falls from a viewing platform. From here you’ll climb to the falls, entering a lush canyon that winds up the creek. Ascend past Silver Falls via a steep rock staircase (there is a cable handrail if you need it), and then follow the trail to Golden Cascade. The trail ends at Sunset Trail, where you will take a right. This trail generally climbs for a bit, with a several dips into gulches as it crosses creeks. Though the woods open up a bit and you might even feel some sunshine, there aren’t any particularly open vistas; however, the trail is well maintained and makes for a pleasant end to your hike.",
    hike_date = '2019-06-05',
    latitude = 37.1728287,
    longitude = -122.22485,
    street = '21600 Big Basin Hwy',
    city = 'Boulder Creek',
    country = 'CA',
    zipcode = 95006,
    distance = 9.7,
    difficulty = 3.6,
    created_date = '2019-05-03',
    picture = 'https://www.rei.com/blog/wp-content/uploads/2019/01/Berry-Creek-Falls-1320x990.jpg'
    )
    hike_six = Hike(
    profile = profile_one,
    title = 'Henry Cowell Park',
    description = "Mostly known for its preservation of large stands of coastal redwood trees, Henry Cowell Redwoods State Park has abundant recreational opportunities and trails to explore. With camping, biking and hiking trails, interpretive exhibits, wildlife viewing, park events and more, the park is a great place to spend the weekend with the family. You'll need to pay a daily vehicle-use fee or present a valid state parks pass. This hike is located in the park's northern Fall Creek Unit and winds through a forest of second-growth redwoods as it passes some old lime kilns. Since no bikes or dogs are allowed in the Fall Creek Unit, the area is much quieter than other areas of the park, though you may still see the occasional hiker or equestrian group.",
    hike_date = '2019-06-16',
    latitude = 37.0499002,
    longitude = -122.0862868,
    street = '1561 Felton Empire Rd',
    city = 'Felton',
    country = 'CA',
    zipcode = 95018,
    distance = 8.4,
    difficulty = 3.1,
    created_date = '2019-05-29',
    picture = 'https://californiathroughmylens.com/wp-content/uploads/2016/08/redwood-grove-henry-cowell-2-640x427.jpg'
    )
    hike_seven = Hike(
    profile = profile_one,
    title = 'Steep Ravine - Matt Davis Loop',
    description = 'Mount Tamalpais State Park is located along the coast just north of San Francisco and has such varied terrain that lovers of both the beach and woods will enjoy exploring this park. With a range of camping options and hiking, biking and horse trails throughout the park, there is more than enough to keep you occupied for a weekend trip. Plus, the interpretive hikes and astronomy nights put on by the Friends of Mt. Tam are educational and engaging for the entire family. To access this hike, park at the limited (but free) parking area on Panoramic Highway, just east of Highway 1. From here, head southeast on Dipsea Trail as it ascends a small verdant canyon before popping out into an open and shrubby meadow with sweeping views of the ocean. At the junction with Steep Ravine Trail, take a left to head up the trail, which is at times rather steep.',
    hike_date = '2019-04-04',
    latitude = 38.18917,
    longitude = -122.9562542,
    street = 'Pierce Point Rd',
    city = 'Inverness',
    country = 'CA',
    zipcode = 94937,
    distance = 7.1,
    difficulty = 3.1,
    created_date = '2019-4-21',
    picture = 'https://www.rei.com/blog/wp-content/uploads/2019/01/Matt-Davis-Trail-1-1320x1043.jpg'
    )
    hike_eight = Hike(
    profile = profile_two,
    title = 'Hamms Gulch - Spring Ridge Trail Loop',
    description = 'Windy Hill Open Space Preserve is aptly named and is generally known for its breezy, grass-covered hilltops. When visiting and hiking around this area be sure to bring an extra long-sleeve layer as the wind can make the temperatures feel much cooler than you might expect. Leashed dogs are allowed on most trails in the preserve, making this a great spot to explore with your four-legged friend. Though there is no camping available within the preserve, it’s an ideal area for hiking, kiteflying, taking in the views and, if you’re lucky, spotting the occasional hang glider or paraglider pilot soaring with the birds. To begin this hike, use the parking area off Portola Road and head out on the Spring Ridge Trail. The going is pretty straightforward for about a half-mile, but when Spring Ridge Trail makes a sharp left, things can get a little confusing. Stay straight onto Spring Ridge Trail Connector to its end at Meadow Trail. Follow Meadow Trail very briefly to reach Hamms Gulch Trail. From here, the going on Hamms Gulch Trail is more obvious. Once you pass Eagle Trail on the left, the path begins to climb, rather steeply at times, toward Lost Trail and Skyline Boulevard. Though there are a few views along the way, most of the trail is well-shaded by the thick woods making this a nice spot on a hot, sunny day. At the junction with Lost Trail, turn left; then when you reach the parking lot, jump across to Anniversary Trail. Anniversary Trail winds around the hill just below the summit, but still has great views. Take a quick side trip on the spur trail to reach the true summit of Windy Hill. From here, you are rewarded with amazing views of the preserve and the Santa Monica Mountains.',
    hike_date = '2019-06-30',
    latitude = 38.18917,
    longitude = -122.9562542,
    street = 'Pierce Point Rd',
    city = 'Inverness',
    country = 'CA',
    zipcode = 94937,
    distance = 7.7,
    difficulty = 3.1,
    created_date = '2019-4-21',
    picture = 'https://www.rei.com/blog/wp-content/uploads/2019/01/Thule-Elk-1320x880.jpg'
    )
    hike_nine = Hike(
    profile = profile_three,
    title = 'Mount Diablo Four Peaks Loop',
    description = 'Located in the hills of the eastern Bay Area, Mount Diablo State Park sits high above the surrounding slopes. Due to its position, the views of the Bay Area from the summit of Mount Diablo are the best around on a clear day. Many visitors simply beeline it to the top, ignoring the plethora of other activities and opportunities the park has to offer. With camping, hiking trails, family programs and guided tours, the state park is perfect for a day visit with the family or a strenuous hike through the hills.',
    hike_date = '2019-05-29',
    latitude = 38.18917,
    longitude = -122.9562542,
    street = 'Pierce Point Rd',
    city = 'Inverness',
    country = 'CA',
    zipcode = 94937,
    distance = 15.4,
    difficulty = 4.8,
    created_date = '2019-4-21',
    picture = 'https://www.rei.com/blog/wp-content/uploads/2019/01/North-Juniper-Trail-1320x990.jpg'
    )
    hike_ten = Hike(
    profile = profile_one,
    title = 'Eagle Peak Out and Back',
    description = "Las Trampas Regional Wilderness is part of the East Bay Regional Park District. Given its size and location in the hills on the east side of the Bay, the park can feel much more remote and less crowded than other places nearby. There is a great hiking, horse-riding and biking trail system throughout the park, with remarkable views and nature viewing opportunities. If you’re a rock nerd, you'll find that the park holds a rich geological history, including faults, ancient beaches and even fossils. To begin this hike, park on Camille Avenue near the junction with Camille Lane. From here, look for the Las Trampas to Mt. Diablo Regional Trail and take it heading southeast along Camille Lane. You’ll follow this through the fragrant eucalyptus trees common in the area's neighborhoods. Once you leave the residential areas and start to ascend into the hills, the grade of the trail increases significantly.",
    hike_date = '2019-06-02',
    latitude = 38.18917,
    longitude = -122.9562542,
    street = 'Pierce Point Rd',
    city = 'Inverness',
    country = 'CA',
    zipcode = 94937,
    distance = 4.2,
    difficulty = 3.0,
    created_date = '2019-4-21',
    picture = 'https://www.rei.com/blog/wp-content/uploads/2019/01/Thule-Elk-1320x880.jpg'
    )

    hike_one.save()
    hike_two.save()
    hike_three.save()
    hike_four.save()
    hike_five.save()
    hike_six.save()
    hike_seven.save()
    hike_eight.save()
    hike_nine.save()
    hike_ten.save()

    Comments(hike = hike_one, profile = profile_four, body='Comment test 1', rating='6').save()
    Comments(hike = hike_two, profile = profile_two, body='Comment test 2', rating='1').save()
    Comments(hike = hike_three, profile = profile_one, body='Comment test 3', rating='9').save()

    HikeGroup(hike = hike_one, profile = profile_one).save()
    HikeGroup(hike = hike_one, profile = profile_six).save()
    HikeGroup(hike = hike_one, profile = profile_four).save()
    HikeGroup(hike = hike_one, profile = profile_three).save()
    HikeGroup(hike = hike_one, profile = profile_ten).save()
    HikeGroup(hike = hike_three, profile = profile_three).save()
    HikeGroup(hike = hike_three, profile = profile_two).save()
    HikeGroup(hike = hike_three, profile = profile_four).save()
    HikeGroup(hike = hike_nine, profile = profile_four).save()
    HikeGroup(hike = hike_nine, profile = profile_two).save()
    HikeGroup(hike = hike_nine, profile = profile_three).save()
    HikeGroup(hike = hike_nine, profile = profile_one).save()
    HikeGroup(hike = hike_nine, profile = profile_five).save()
    HikeGroup(hike = hike_nine, profile = profile_seven).save()
    HikeGroup(hike = hike_nine, profile = profile_ten).save()


def delete_both(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Hike = apps.get_model('hike', 'Hike')
    Comments = apps.get_model('hike', 'Comments')
    HikeGroup = apps.get_model('hike', 'HikeGroup')
    Comments.objects.all().delete()
    HikeGroup.objects.all().delete()
    Hike.objects.all().delete()
    Profile.objects.all().delete()
    User.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0003_auto_20190524_1200'),
    ]

    operations = [
        migrations.RunPython(seed, delete_both)
    ]
